name: CI-Check
on:
  workflow_dispatch:
  push:
    branches: [ "**" ]
  pull_request:
    types:
      - opened
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Test
      run: dotnet test MinecraftLaunch/MinecraftLaunch.csproj
  test_build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Test
      run: dotnet build MinecraftLaunch/MinecraftLaunch.csproj
